### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#123]
I've used Gossip today for about 18 minutes straight browsing multiple notes and clicking to "update metadata" a lot of times for a lot of people. Also posted probably more than 10 notes, between new notes and replies to others. At some point the interface began to hang and everything become a lot slower. It was quite sudden. I don't understand exactly why that happened, but I got afraid and closed everything. My list of followers is less than 10 people (I did add two new profiles to the list while browsing).

**Comment by mikedilger** [comment]
Ok. I've had similar problems but each time I did I thought I fixed it. What typically happens is the overlord gets deadlocked, waiting for a lock that somehow is never going to unlock.  Which commit were you compiling from?  I'll see if I can find it by just looking around.

**Comment by fiatjaf** [comment]
d9cf30dc7a1d3e4aae36b63a7231da0ae7daf644

But if you kinda know the reason and expects it to happen again maybe let me wait until it happens and I will provide more info.

Or hopefully it will happen with you first.

**Comment by mikedilger** [comment]
Just to be safe, I should probably make sure that certain kinds of activities always leave some kind of log trace, so if it gets really slow and it's because it's continually connecting to HTTP endpoints to fetch avatars over and over again (it did that once while I was still coding that part), you'd at least see a constant stream of log messages and know to close it immediately.

**Comment by mikedilger** [comment]
Haven't seen this behavior for a while. At this point, I'm going to close this and we can reopen if it happens again.
