### ISSUE TITLE
Duplicate other known relays

### ISSUE THREAD

**Issue by thesimplekid** [mikedilger/gossip#174]
Some relays are appearing twice in the other known relays section, once with a / at the end and once without. 
![Screenshot from 2023-01-28 16-05-31](https://user-images.githubusercontent.com/8606367/215291143-02d9ac75-f76a-4520-92f1-24b86238d7ad.png)

**Comment by mikedilger** [comment]
I'm fixing this in nostr-types first.  url.inner() is being replaced with url.canonical().

I can't actually rewrite the non-canonical url content or signature verification would fail. But I can make the interface such that if you want the Url in string form, the only way to get it (outside of serialization) is via url.canonical() which will strip these slashes.  [serialization will preserve the ugly non-canonical form]

**Comment by mikedilger** [comment]
Well, I pulled on that thread and the whole sweater unraveled.  I've almost finished knitting a new sweater that doesn't have that loose thread.  I can't believe how many lines of code had to change to fix this.

Of course I'm fixing more than just the '/'.  I've gone for three types:

`UncheckedUrl` - a type wrapping a UTF-8 string that is supposed to be a URL but could be anything

`Url` - a type wrapping a UTF-8 string that is validated as a URL with a scheme, and authority, and isn't a localhost, and has some canonicalization (like lowercase scheme)

`RelayUrl` - a type wrapping a UTF-8 string that is validated as much as `Url` but also must be websockets and must not have a trailing slash (since it must have an authority  '://' is never seen as a trailing slash)

Then of course I wanted to change my types throughout.  Hence the sweater analogy.

I'm treating database records as UncheckedUrls and converting them into RelayUrl as we load them.

But I'm also writing a schema update that will convert and merge the data.

**Comment by mikedilger** [comment]
fixed
