### ISSUE TITLE
Handle URL uppercase schemes

### ISSUE THREAD

**Issue by garyray-k** [mikedilger/gossip#179]
Gossip crashes with case sensitive non-"wss" in relay url
This might be an issue for https://github.com/mikedilger/nostr-types but I wanted to leave it her as well since it renders the app unuasble.

<img width="1258" alt="Screenshot 2023-01-30 at 6 39 58 AM" src="https://user-images.githubusercontent.com/39040273/215511186-bd085b00-3718-4677-9a8c-4180e2e463ff.png">
I get an error if there is a relay using "Wss" as the protocol prefix. Additionally, I can resolve this issue by making the passed string lowercase on Line 63 of src/db/relay.rs `let url = RelayUrl::try_from_str(&s.to_lowercase())?;`

However, I then encounter:
![Screenshot 2023-01-30 at 9 55 00 AM](https://user-images.githubusercontent.com/39040273/215511751-23dd24c3-a3a7-4eeb-bed7-5aff9fb98405.png)

It appears I have relays being advertised in a case-insensitive way or advertised using another protocol.

**Comment by mikedilger** [comment]
My recent giant URL fixing commit has done this.

Lowercasing the entire URL isn't right, because only scheme and host are case-insensitive; path isn't (even though relays generally aren't using a path).  I assumed http::Uri was normalizing the URI but I guess it is not.

I can't fix this right away I have to go into work.  If you were inclined, `nostr-types src/types/url.rs` in `Url::try_from_str()`, instead of using `format!` on the uri we should probably copy their Display code but put in the to_lowercase calls on the scheme and host part (see https://docs.rs/http/latest/src/http/uri/mod.rs.html#1025-1043)

Anyhow that is my thinking at the moment.

**Comment by garyray-k** [comment]
Agreed. It should just be ignored/skipped if it's invalid.
Thanks for the context.

**Comment by mikedilger** [comment]
Ok I managed to fix this before 8 o'clock when work starts.

**Comment by garyray-k** [comment]
😆
Thanks! Went to merge and had a conflict. Then saw your commits. 
7/5 stars for responsiveness.
