### ISSUE TITLE
delete packaging/arch

### ISSUE THREAD

**Issue by soloturn** [mikedilger/gossip#217]
mike, there is now two arch linux packages in AUR:

- https://aur.archlinux.org/packages/gossip
- https://aur.archlinux.org/packages/gossip-git

you want to remove the packaging for arch in this source tree?

**Comment by mikedilger** [comment]
Cool.

Why does it need 'mold'?  What is wrong with the default linker?

A couple bugs in the PKGBUILD files:

* search for 'mtkdir', remove the line (typo in the gossip-git variant command name, but also not necessary with the next change)
* the next line that installs the .desktop file needs to end in "/${pkgname}.desktop"  instead of ending in just "/", then it will create the directory automatically

**Comment by mikedilger** [comment]
I see I have access. I guess I'll make these changes.  But I'd like to hear about mold and lto and how they interact first.

**Comment by mikedilger** [comment]
done
