### ISSUE TITLE
"Dependency is not satisfiable: libssl1.1 (>= 1.1.0)" when trying to install

### ISSUE THREAD

**Issue by zyklopisch** [mikedilger/gossip#232]
"Dependency is not satisfiable: libssl1.1 (>= 1.1.0)" - this error appears when I am trying to install within Linux Mint newest - any idea how to circumvent?

**Comment by mikedilger** [comment]
I don't know, it looks like a package conflict in your OS.  Not something I can help with.

**Comment by stupicorn** [comment]
Same when installing a pre-compiled `gossip-0.4.0-debian` in Ubuntu 22.04 LTS.

**Comment by mikedilger** [comment]
I presume "satisfiABLE" means it cannot be satisfied, which is different from that it hasn't been satisfied.  Which means it is impossible to install gossip on such systems.  Because those systems refuse to install libssl 1.1.0 or greater.  Why? I don't know.  Maybe the newer versions were renamed to something else, maybe your system is old, who knows?

Gossip can run without libssl.  But not from this precompiled package.

This is one of the reasons why I don't recommend people use packages, but instead clone this repo and compile it yourself.  The compile process will figure out what your system has and use whatever your system has.  I can't build a package that "just works" on everybody's system when everybody's system is different.

Maybe next version I'll switch to rustls which does not depend on any ssl library.

**Comment by mikedilger** [comment]
I've switched it over on master (pushing soon), but I can't patch version 0.4 with this until it's proven stable (the fix might break something else), so it might take few days to a week for this "fix" to land in 0.4.1
