### ISSUE TITLE
No connection attempts

### ISSUE THREAD

**Issue by 0xbabo** [mikedilger/gossip#241]
I've added a public key and a couple of relays, but I'm not seeing any connection attempts.

Built current head https://github.com/mikedilger/gossip/commit/df8f88e780f56c1ebc8e37a0071aecbadc0c5267 on M1 Mac with default build settings. 

Logs are not very helpful. How can I debug this? 

<img width="714" alt="Screenshot 2023-02-17 at 12 26 03 PM" src="https://user-images.githubusercontent.com/110633279/219786593-5771909f-80f2-405e-b364-61df4fd81294.png">

```
> ./gossip
 INFO Database is at version 23
 INFO Loaded 0 reply related events from the database
 INFO Loaded 0 feed related events from the database
 INFO Loaded 0 relay list events from the database
 INFO Done picking relays: All people accounted for.
```

**Comment by mikedilger** [comment]
It looks like you have only ticked "read" relays.  I know you just added a public key so it doesn't seem like you would need write relays (you can't write to them without a private key), but actually you do.  Gossip needs to read data you wrote from previous clients, and it does it from your "write" relays (because that is where they were written to). That includes your Contact List.

For better logging, try the `run.sh` script which turns on more logging.

Are you following anybody?  If you aren't following anybody, it has no reason to connect to anything.  Gossip doesn't support the notion of a global feed.  Go to the "People > Followed"  and "PULL" the people you follow.  Let me know if it worked.  At first they won't have metadata, so then try "Refresh Metadata".  Also try restarting (sometimes that helps)

**Comment by 0xbabo** [comment]
Fixed by ticking some "write" relays. 👍
