### ISSUE TITLE
Building for Windows on Linux

### ISSUE THREAD

**Issue by CalebFenton** [mikedilger/gossip#253]
I wanted to compile gossip on Linux for Windows. I want to use gossip on windows but I hate developing on windows.

I'm not familiar with rust but wanted to share how I got it working so you could add do documentation if you wanted or people could search for it in the issues and find it. Here's what I needed to do in addition to your helpful instructions.

- install `gcc-mingw-w64` (debian)
- set cargo to build for windows `rustup target add x86_64-pc-windows-gnu`
- then I built with `RUSTFLAGS="-C target-cpu=native --cfg tokio_unstable" cargo build --target x86_64-pc-windows-gnu --release`
 
I'm not familiar with Rust so this may look stupid but neither of these commands worked:

- `RUSTFLAGS="-C target-cpu=native target x86_64-pc-windows-gnu --cfg tokio_unstable" cargo build --release`
- `RUSTFLAGS="-C target-cpu=native --target x86_64-pc-windows-gnu --cfg tokio_unstable" cargo build --release`

**Comment by mikedilger** [comment]
I think the `target-cpu=native` part can't work in this situation because the compiler can't peek at the actual CPU it is going to be run on to optimize for that, which is on a different machine.  So just leave that one off.  And given that state of affairs, there's no reason to override RUSTFLAGS so you won't need the "--cfg tokio_unstable" either.  Meaning this should work (I have not tried it):

`cargo build --target x86_64-pc-windows-gnu --release`

And BTW you can do that for any target including the very sexy `riscv64gc-unknown-none-elf` or even a custom target defined in a JSON file.

**Comment by CalebFenton** [comment]
Thanks for the tips. `cargo build --target x86_64-pc-windows-gnu --release` works great.

**Comment by mikedilger** [comment]
I'm gonna close this and people can find it by searching closed issues.
