### ISSUE TITLE
scroll to note

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#267]
When you enter a thread, the highlighted not is not scrolled into the view.

If we recorded the y-offset of each note in the feed, we could scroll to any note by id.

**Comment by bu5hm4nn** [comment]
I believe this is complete

**Comment by bu5hm4nn** [comment]
I just looked into this. Doing scroll-to with egui is very easy as you can just call `scroll_to_me()` from the response of the post frame. 
But because the feed is constantly changing as new notes are found and come in, the big question is, when do we do the scrolling without annoying the user? The best answer I have is: constantly `scroll_to_me()` until the user does any scroll input, then stop automatic scrolling. But I'm not sure it's worth the effort.

**Comment by mikedilger** [comment]
Can we just do it only once when we enter the thread view?  Set some variable to indicate that we have already scrolled so it doesn't keep doing it.

**Comment by bu5hm4nn** [comment]
Implemented in 7913e2b92cae5658bc6134d0a5547b73e34a6351
