### ISSUE TITLE
gossip can't display None-English text correctly

### ISSUE THREAD

**Issue by LifeNT** [mikedilger/gossip#271]
None-English text displayed square

**Comment by mikedilger** [comment]
I want to support more characters.  If you know which characters you want to see (Tamil, Hebrew, Cherokee, Arabic, CJK JP, etc) let me know.  I will make different font sets into features so you can compile in the fonts you understand and skip the ones you don't.  And I need to know which characters people are wanting because I probably won't add them all as there are more than a hundred.

**Comment by LifeNT** [comment]
Okey，please fix chinese: include simple chinese and tranditional chinese font, or can I fix it myself?

**Comment by mikedilger** [comment]
I will add cargo features for it.  If you want to do it yourself, and you beat me to it, please feature gate it.

**Comment by mikedilger** [comment]
Ok I have added it.  Compile with "--features=lang-cjk"

**Comment by LifeNT** [comment]
thanks, I wait for your release.
