### ISSUE TITLE
Direct messages placement

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#281]
Direct messages are currently shown in the Main feed and Conversations.
I think they should be shown first of all in the **Inbox**, never in the Conversations and maybe in the Main feed to give them more visibility.

**Comment by bu5hm4nn** [comment]
I think they should have their own view as they do in other clients

**Comment by mikedilger** [comment]
Why not put them in your inbox with everything else directed towards you?  Why mimic SMS like the other apps do? Because that's what people expect?  I like the idea of one place to get all my messages... and of course we still need the "5 unread messages" thing, but that should includes DMs and non-DMs IMHO.  I think we can have a lock icon on the message, and the reply button can have a lock near it, and when you reply it can have a lock icon or even show a different color, and it will be clear you are replying to just that person via a DM.

**Comment by dtonon** [comment]
My proposal live in the actual context of read-only DM: now the Inbox seems the right place.
When the reply will be implemented I agree with @bu5hm4nn that a proper section is need because in the a common action is to enter the messages section to search a contact or continue an older conversations, and this is not possibile at all with the Inbox paradigm; Inbox can continue to act as notification central point.
I think we should do what people expect until we cannot offer a better UX, this is sometimes a try and catch process of course.

For this issue is enough to move the dm notifications as proposed.
Then we can move them out of the Main feed as soon we are able to put a little dot to hint new messages near the feed name (the number is not so import, imho).

**Comment by mikedilger** [comment]
I removed them from the main feed.  1 line change.
