### ISSUE TITLE
Error on start: there is already another table or index with this name: old_person_relay

### ISSUE THREAD

**Issue by 0xtrr** [mikedilger/gossip#308]
Built it from source on the latest master branch but when I try to run the program, I get this error:

```bash
gossip git:(master) ./target/release/gossip
2023-03-13T16:09:13.967593Z  INFO src/db/mod.rs:132: Upgrading database to version 31
Error: Sql(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("there is already another table or index with this name: old_person_relay")))
```

**Comment by mikedilger** [comment]
I think this particular error can only happen if you tried it once and it failed, and then you tried it again.  Not blaming you, just saying this because this error is useless to me, but the original error would have helped more.  Nonetheless I'm pretty sure I know what the original error was.

I will change the SQL in a way that will prevent this in the future for other people. But that won't help your case.

Now you have to manually rename a table in sqlite.  Run sqlite3 on your database, and then do this:
````
ALTER TABLE person_relay RENAME TO just_in_case;
ALTER TABLE old_person_relay RENAME TO person_relay;
````
The logic is that I moved your original person_relay to `old_person_relay`, then I tried to populate a new `person_relay` table with the new structure, and that population failed.  So you don't really need that new under-populated `person_relay` but you must preserve the `old_person_relay` which has your real data, and rename it back.

Then wait for me to push the new code.

**Comment by mikedilger** [comment]
Please let me know when you have tried this so I can address further issues or close

**Comment by 0xtrr** [comment]
Where is the sqlite file supposed to be stored? I can't find it

**Comment by mikedilger** [comment]
Go to "Help > About" and it will show you where.

**Comment by 0xtrr** [comment]
I can't open the application at all so not able to go to the about page.

**Comment by mikedilger** [comment]
https://docs.rs/dirs/4.0.0/dirs/fn.data_dir.html

then append "/gossip/gossip.sqlite"

**Comment by 0xtrr** [comment]
Ah, finally found the db. Deleted the whole gossip data folder and now everything works again. Thanks Mike!
