### ISSUE TITLE
Feature Request: Add Repost button next to "Quote" button

### ISSUE THREAD

**Issue by InnocuousFinch** [mikedilger/gossip#315]
Use case: I want to click and quickly repost a post, similar to how Twitter does a retweet. Most Nostr clients have this functionality. 

I believe they are using the event kind 6, but it's not listed as the official kind [here](https://github.com/nostr-protocol/nips#event-kinds) so I'm not really sure if there is an agreed upon way to do this.

**Comment by mikedilger** [comment]
You can start a post, press the quote button under the post you want to repost, and then send.  The quote icon is a bit strange.  I know that's not a single-click operation.

I'll leave this open so we can do better.

**Comment by InnocuousFinch** [comment]
When doing this, it shows up differently than a true repost. Even shows up differently in gossip. If I follow your suggestion, it will not show up as `REPOSTED` in gossip since the post's `event.kind` is not of type `EventKind::Repost`

@TonyGiorgio can confirm as well.

**Comment by mikedilger** [comment]
There is no "true repost" and this area of nostr is still undergoing upheaval. Both @dtonon and @bu5hm4nn are working with me to render reposts appropriately but there are lots of variants and lots of opinions too.  I'm not going to be working on repost related work as there would be too many cooks in the kitchen.  But I will say that fiatjaf was against kind-6 and because in-the-wild kind-6 reposts were not following the NIP, he removed the NIP (he drafted that NIP thinking it reflected current practice, but it didn't).  He's now settled about fully serializing the event in the body, but wants someone else to please NIP what they are doing.  Nobody has.  So there is no official repost, kind-6 is unofficial and different clients have gone in different directions on this.  There are kind-1 mentions that are supposed to be treated like reposts too (but apparently only if there is no content other than perhaps a reference to a tag).  This is a far larger issue  than just a feature request for gossip and it needs to be agreed upon as a communitiy first.  I hope you can understand the difficult position I am in.

**Comment by bu5hm4nn** [comment]
I think this is now done in current master, no?
