### ISSUE TITLE
Handle lack of EOSE

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#33]
We should still update last_fetched even if we don't get an EOSE.

**Comment by ok300** [comment]
FYI: lack of EOSE typically means the relay hasn't finished sending the initial batch of messages. Sometimes it can take a few minutes if the filters are too generic, or if the relay is overloaded.

I'm building a similar app and I'm taking the opposite approach: only save the timestamp on EOSE. I then use this timestamp as `since` filter on next restart, such that I only do a "full sync" once per relay when the app is first intalled. Any subsequent app starts deal with deltas or incremental syncs.

**Comment by mikedilger** [comment]
But nip-15 is optional. So there could be a relay that will never send an EOSE.  I want to be robust enough to handle that even if I don't use any such relay.  Maybe by setting a last fetched at least at the time of the last event I received.

**Comment by ok300** [comment]
Good point.

**Comment by mikedilger** [comment]
This is handled by setting eose immediately on every relay that does not support NIP-11.  So I'm closing this (though I should probably fix misparsed NIP-11s)
