### ISSUE TITLE
Feedback on Gossip as a first-time user

### ISSUE THREAD

**Issue by dave-underwood** [mikedilger/gossip#380]
Hi Mike,

Thank you for Gossip (and hello to a fellow Kiwi!)

I just had two pieces of feedback. I apologise if these are known issues and I am telling you something you already know.

1. After I had created my public & private keys using Gossip, I was interested to test the interoperability of the nostr protocol, so I tried to log into the Damus app on iOS using my newly-generated private key. However the Damus app would not accept my private key (I got the message "invalid key"). The app would accept my public key. Do you know why my Gossip-generated private key would not be being accepted by the Damus app? The one thing I noticed is in the Damus app it asks for a key starting with 'nsec1' and the private key I got from Gossip starts with 'ncryptsec1...'

2. I was keen to 'verify my public key on nostr' for https://nostr.directory/. However the instructions on that site say to 'Make sure you properly tag our pubkey (@5e7ae58...) with a p tag. (https://github.com/nostr-protocol/nips/blob/master/01.md#other-notes)'. I am probably misunderstanding or blind, but I couldn't see a way to set 'p tags' in Gossip?

Thanks again,
Dave

**Comment by mikedilger** [comment]
Hello fellow Kiwi and thanks for the feedback!

1. ncryptsec is an encrypted secret key, that follows https://github.com/nostr-protocol/nips/pull/133 (unmerged NIP-49) which AFAIK nobody else ever implemented.  You have to copy the 'nsec' to use Damus, and if you do you weaken it because you just exposed it in your cut-and-paste buffer and via any method you used to transfer it in the clear.  To do this, find the "Raw Export" section of your keys, enter your passphrase, and press "Export Private Key as bech32".

2. Those instructions aren't very user friendly.  To add a 'p' tag, that happens whenever you tag someone with an '@'. In gossip it is very clunky currently.  Start a draft, in the box that says "@username" start typing their display name.  Then press the '@' button for a pulldown menu of people.  Pick the account.  It will inject a string into your message, and it will also add the 'p' tag that matches when you send it.

Hope that helps.

**Comment by dave-underwood** [comment]
Thank you so much Mike 👍
