### ISSUE TITLE
[Feature request] Automatic relay selection

### ISSUE THREAD

**Issue by vitarb** [mikedilger/gossip#382]
Hey folks,

I embrace decentralized model of nostr and it's nice for users to finally have full control over their identity online.
However amount of time needed to discover, setup and maintain a list of healthy relays seems a bit too high to me.
I think there should be a convenience mechanism (opt-in or opt-out) that would automatically discover and pick relays for you.
This would simplify onboarding of new users and will also make clients more robust.
I understand that this is a complicated technical problem, and not sure if this is possible to do in a fully decentralized way (maybe it is okay for convenience features like this to be centralized?), but I think this feature is desperately needed if we want to see any serious adoption of this product.
I encourage discussion on this topic to see if we can come to any sort of conclusion.

**Comment by mikedilger** [comment]
I am not interested in battling with relay operators about who gets to be hardcoded into gossip.  I don't want to have to continually maintain such a list, removing relays that no longer operate.  I don't want to contribute to the accidental centralization of nostr onto the relays that I happen to add as defaults.  I don't even want to subtly influence people, nudging them towards particular relays that I personally like.... I hate being "nudged" myself so, in respecting my userbase, I choose not to nudge them.

Furthermore, relay choice is something that users really do need to think hard about.

I fully understand that this makes gossip harder to setup.  Some users appreciate the blank-slate that gossip gives them.  Others find it annoying.  I can't make everybody happy.

I'm closing this because I won't do this. But others are free to have a conversation here after it is closed.

**Comment by mikedilger** [comment]
Once setup, relays are discovered.  We are working on adding lots of functionality in this regard, where relays have their own page, where that page has a "sign up" button for the relay, where it explains their policies and features (NIP-11), gives their historical performance stats, etc... making a one-stop place for users to understand each relay.

BUT that will only happen after gossip discovers the relay, or the user manually adds it.

**Comment by vitarb** [comment]
Bitcoin itself has pretty robust mechanism for node discovery, perhaps we could implement something similar in nostr, like a DNS seeds and gosip between relays, then selection based on ping/availability.

**Comment by mikedilger** [comment]
Gossip has relay discovery already. My client knows about 333 relays, and I only typed in 3 or 4.

But it cannot discover new relays until it gets connected in the first place, so you will always have to type in the first few.
