### ISSUE TITLE
Gossip doesn't load relays on Whonix

### ISSUE THREAD

**Issue by protocoel** [mikedilger/gossip#384]
Hey Mike, I'm using a fresh install of Whonix. Everything works well on my Whonix through the Tor setup except Gossip. 

I installed the .deb file using dpkg. 

## The Problem
I imported my private key from a different nostr client. It correctly shows the associated public key and nothing else. 
I don't see any relayed being fetched. No live feed. No followed list. 
So, clearly, it isn't able to connect to the internet. 

## What I've tried
I tried a few things. 
1. No errors on terminal when I start with the command `gossip`. 
2. I tried `torsocks gossip`, no luck. 
3. Searched github issues. 
4. I don't have `ufw` firewall installed. 
5. The internet works on Brave browser(tested to see if 3rd party apps work). 

I'm new to Whonix, I saw that Whonix was mentioned here when proxy setup was mentioned in one of the [issues](https://github.com/mikedilger/gossip/issues/218#issuecomment-1430319736), where you said Gossip x Tor should work out of the box on Whonix. Please help me figure this out. Ty.

**Comment by mikedilger** [comment]
First, congratulations on a great setup. I've run gossip on whonix myself and I think for anonymous social media identities it is a good solution.

I think you may have misdiagnosed the problem. Gossip probably can connect to the Internet. I can't say for sure, you'll have to work that out.

Rather, the problem is that gossip requires some manual setup. Read the instructions under `Help > Getting Started` for "Existing Nostr Users".  In particular, you have to manually enter some relays where you know that your configuration files (metadata, contact list, relay list) are at. Then you probably need to restart (I can't remember if you do or don't, but it can't hurt).  Then you need to go to `People > Followed` and `Overwrite` which pulls in your contacts.  Then press `Refresh Metadata` to refresh all their metadata.

Let me know if that helped or not.

**Comment by protocoel** [comment]
It worked! Thank you so much. I didn't know that nothing would show up without these configs.
