### ISSUE TITLE
Visualization: Make whole conversation thread or branch collapsable with one click

### ISSUE THREAD

**Issue by gustavonmartins** [mikedilger/gossip#386]
Hi, I have two ideas to improve tracking better conversations:

1)  it would be very nice to show on my inbox, or "main feed" the threads as a whole, not just fragments of someones answer.

It would also be good to navigate on it with clicks like in libreddit, or hacker news.

This would avoid getting lost in fragments of conversations, keeping the overview and context of each message. Here are some examples of whole thread view with collapsible branches:

https://libreddit.domain.glass/r/memes/comments/13rifnc/absolutely_not_i_would_rather_die_than_pay_that/
https://news.ycombinator.com/item?id=36056408

A Hacker News client for Android also has this, in a mobile friendly way:

https://github.com/hidroh/materialistic

2) It would also be nice that when I ask to see all of a users posts, that I can select "show only the posts STARTED by this user (in which he is the root of the conversation - I think its when his message has no "e" field). This would be useful for me to select users by their ability of creating new interesting conversations.

Thanks!

**Comment by mikedilger** [comment]
1. Okay we could do 1, but if we showed the threads in your inbox or main feed, we would need to start out with threads closed, and only load the posts when you opened them, or else it would be a huge performance cost of loading all the threads of the main feed that you never open.  Does that make sense? Right now if you click the circle dot on the right, dives into that thread, but does so as a separate page.  Also, this would only make sense if the switch was on "Main posts" and not "include replies".

There are multiple ways to skin a cat, and we would need some discussion to see what other people think.

2. Yes, we don't have a switch for that view like we do on main feed and inbox.  This is also true of "My Notes".  Again, we would need some discussion of possible new feed designs.

**Comment by namoscagnm** [comment]
For me personally, I prefer to have threads starting closed as you suggested, as it would be with email. This would help me reduce noise and distraction.

I do not understand the difference between inbox, mainpost and include all replies. It always confuse me, so I cannot say what is the benefit of changing it.

Some users might not like my suggestion, so this could be also implemented as something optional.

In general, I believe that many users will have their own needs. I was guessing if its possible to decouple the UI from the rest of the software, so that coding new wishes get easier for the team. Another possible idea, as someone suggested, would be making the user interface scriptable, so users can adapt to their needs without having to overload the developers. We could even get to a point where the scripts are shareable.

Thanks so much for your time

**Comment by namoscagnm** [comment]
Hi,  I had a change to use more your program and actually the point 1) is already implemented.

I just have to click on "Main feed" and use "Main posts" instead of "include replies" and I can have the thread roots shown.

Im actually now what you understood from my post :)

If anyway you found my first post useful, could you please explain the way you understood it and how it would be useful?

Thanks!

**Comment by mikedilger** [comment]
It is possible that in the Main Feed with "Main Posts" being on (only showing root posts), that you could unfold a post to see it's replies, and also continue seeing all the other root posts above and below it.   But instead, you have to press the circle on the right and you only see that post with it's replies.  So that's the difference I thought this was about.

I like the "Include Replies" switch so I can see, in chronological order, every event that comes in regardless of threading.  In that view you can still press the circle on the right, and it highlights that post within it's thread context.

**Comment by namoscagnm** [comment]
Ok, I found again what was confusing me:

Current beaviour:

When I click People -> Followed, then I clike someone and "View their posts", I can see not only the conversations started by the person, but also some comments of the person which belongs to a conversation started by someone else.

Desired behaviour:
When I click People -> Followed, then I clike someone and "View their posts", I have the option of showing ONLY the conversations STARTED BY the person. If the person is just answering to a topic started by someone else, Id like to have the option of not seeing it.

In the example below, I the first message should not appear, but the second should still appear:

![image](https://github.com/mikedilger/gossip/assets/15790478/773c6e61-2df6-492c-a4de-2a9b342b344f)

**Comment by bu5hm4nn** [comment]
We now have this switch at the top that solves this issue (include replies YES/NO)

<img width="590" alt="Screenshot 2024-03-07 at 21 32 36" src="https://github.com/mikedilger/gossip/assets/3328670/b56cfc62-5126-407e-9864-a3d840d3e22d">
