### ISSUE TITLE
allow to follow someone with only npub

### ISSUE THREAD

**Issue by ulrichard** [mikedilger/gossip#390]
Most people only share their npub. When I want to follow them in gossip, I also have to provide a relay url. I understand why this is on a technical level, but from a UX perspective this is not great at all. Or maybe there is something in the GUI that I didn't see?
The client would be much faster than me at trying a few known relays to see if they have data for this npub.

**Comment by mikedilger** [comment]
I hear what you're saying. Maybe it should try all your read and discover relays.

**Comment by ulrichard** [comment]
Exactly, starting at the ones with the most "Num Keys"

**Comment by splix** [comment]
I also found this part a bit complex to use. I want to refactor the screen and make it just as a single input element which should automatically determine the type (nprofile, dns, npub). And for npub have an _optional_ url for a relay. 

@mikedilger is that ok to do?

**Comment by mikedilger** [comment]
I have no problem with combining the fields and figuring out what the put in.

But I have a problem with accepting just an npub. Because people are going to be a lot more confused when that person's posts never show up.

**Comment by splix** [comment]
Never shows up because of no relays?

**Comment by mikedilger** [comment]
Different developers imagine nostr working in different ways, and we tug-of-war with each other.  I imagine a world where Richard Dawkins uses wss://richarddawkins.co.uk/ as his nostr relay and https://richarddawkins.co.uk/ as his website.  

How could gossip figure this out without typing it in?  Well, if there is a discovery service like wss://purplepag.es/ that specializes in serving kind 10002 relay lists, then gossip could lookup Richard Dawkin's relays and you wouldn't have to type it in.

But unfortunately most nostr clients aren't publishing kind 10002 relay lists for finding people.  And if they do, aren't publishing them broadly enough to be found.  It's not reliable to just go to wss://purplepag.es/ and expect everybody you want to follow has a kind 10002 registered there.

So while nostr is still finding it's feet, we need this much more reliable way to follow someone, and that is to enter a relay that they post to.

We could in the mean time have a more dynamic process that tries to find their relay list, and only asks you to type it in if it can't find it. These kind of multi-step asynchronous processes are difficult to code in gossip as currently architected.

**Comment by splix** [comment]
@mikedilger I understand your concern, and for that world it would need some discovery mechanism. For the current world it seems to be a rare case. There are a few popular relays and most of popular people exist at least at one of them, as well as other users read from those relays. So it seems that for an average user that already follows few popular accounts and adding a new one it works without specifying a relay. 

For testing of this feature I chose 3-5 relays (without any preference, just something that I see on Jack's profile for example) and then tried to follow few accounts (again, nothing rare, just something that show on popular directories, some popular accounts) and it worked perfectly. I fully understand that it would not work for every user and for every account though. In this case the Follow dialog has an optional field for a Relay.

**Comment by splix** [comment]
btw, I think it can be improved by additional UI. Right now Gossip tries to follow the specified account immediately and the used doesn't see if there is any problem. I think there should be an additional panel shown right after clicking "Follow" button. That panel may show progress of resolving the account, show errors if any, or ask for a relay if Gossip cannot find the account with current list.

**Comment by jadijadi** [comment]
Another idea might be checking a few popular relays after the user entered the npub and if the npub is found on any of them (and if the user has not entered a relay yet), fill the relay using that.

**Comment by cryptoquick** [comment]
I like that idea, @jadijadi. It would be nice to pre-fill the relays screen with a few popular relays, how other clients do, and then maybe have a checkbox for "Default" or something like it, which would be checked whenever an npub is added.

**Comment by mikedilger** [comment]
All of you need to think more about centralization.  Offering a few "popular relays" centralizes nostr.  One of the main reasons I wrote gossip at all was to be a force against centralization.  It doesn't matter if something works most of the  time in today's world, if I code it to look at "popular relays" then gossip is pushing people towards those central relays.  I won't be doing that.

Also, I think gossip should work just fine 20 years from now after all the current relays have long since died and a totally different crop of relays exists... without anybody having to change some hard-coded list of relays in the code.

Furthermore, there may be isolated networks of relays and clients that don't even interact with any of us. Gossip should work for them too, even though they don't interact with the relays you and I do.  Maybe some church group somewhere that doesn't want to be on the Internet at large, but only connected to each other.

What I intend to do is (and this will be a while as I have a few things in the hopper first):

When you start gossip, or anytime when you want to check that your setup is sane, there will be a wizard that helps you get setup well.  One of the steps is to enter quite a few "discovery" relays where you wish to find people.  Unfortunately due to a chicken-and-egg type of problem, they DO need to enter these discovery relays.

Later when following someone with only an npub, it will check the discovery relays and find the kind 10002 and the user won't need to enter relays.  If that process fails, that followed user will be flagged somehow as "missing in action" and they can correct it by entering a relay to find them at.

**Comment by cryptoquick** [comment]
Sure, that makes sense and sounds good.

**Comment by sysfu** [comment]
> All of you need to think more about centralization. Offering a few "popular relays" centralizes nostr. One of the main reasons I wrote gossip at all was to be a force against centralization. It doesn't matter if something works most of the time in today's world, if I code it to look at "popular relays" then gossip is pushing people towards those central relays. I won't be doing that.
> 
> Also, I think gossip should work just fine 20 years from now after all the current relays have long since died and a totally different crop of relays exists... without anybody having to change some hard-coded list of relays in the code.
> 
> Furthermore, there may be isolated networks of relays and clients that don't even interact with any of us. Gossip should work for them too, even though they don't interact with the relays you and I do. Maybe some church group somewhere that doesn't want to be on the Internet at large, but only connected to each other.
> 
> What I intend to do is (and this will be a while as I have a few things in the hopper first):
> 
> When you start gossip, or anytime when you want to check that your setup is sane, there will be a wizard that helps you get setup well. One of the steps is to enter quite a few "discovery" relays where you wish to find people. Unfortunately due to a chicken-and-egg type of problem, they DO need to enter these discovery relays.
> 
> Later when following someone with only an npub, it will check the discovery relays and find the kind 10002 and the user won't need to enter relays. If that process fails, that followed user will be flagged somehow as "missing in action" and they can correct it by entering a relay to find them at.

Funny, this discussion calls to mind a similar conflict that Elementary OS had regarding inclusion of flathub as a default or one-click repository for the Appcenter. Seems that centralization of apps is already taking place at flathub.org so users are wondering why the Appcenter doesn't include flathub as a default repo. The eOS project founder [responded with a similar rationale](https://github.com/elementary/appcenter/issues/1748#issuecomment-963424996).

Maybe a solution would be to randomly a relay for the user if they don't know what to enter, but it seems that open the whole new can of worms discovering which relays can reach the given npub. I agree that forcing users to choose a relay is probably a UX fail but I'm also averse to incentivizing centralization.

As someone brand new to nostr, why do people share npubs instead of nrofiles, if the former requires relay info?

**Comment by mikedilger** [comment]
I've added code to allow adding relays to people post-facto. I've also improved fetching someones relay list. And I've made it clear which users do not have relay information yet (in the person list).  All of that is on unstable.

Subsequently, I did what you all wanted here. Now you can follow with just an npub, hex, nprofile, or nip05 address all into a single field and it figures it out from there.
