### ISSUE TITLE
NIP-26 Delegation 

### ISSUE THREAD

**Issue by francuss** [mikedilger/gossip#415]
Hello friends,

I imported my public key and my delegation tag in Gossip, to avoid risking my private key.

But Gossip Profile writes that I need to unlock my private key to edit/save metadata.

So which is the purpose of the effort to create and maintain a delegation tag, if then I need to import my private key nevertheless?

Best

**Comment by mikedilger** [comment]
You can't write data without having a private key of some sort.

You should have an offline keypair that you do not import, not even the public key of it, because that's not how delegation works.

You should have an online keypair that you import or generate in gossip that includes it's private key (not your offline private key).

The delegation tag lets other clients know that this online keypair represents the offline one.

I have never used this myself.  @optout21 (catenocrypt) added the delegation code, so he might be able to help further.

**Comment by francuss** [comment]
Many many thanks @mikedilger, your explanation is very clear.

So practically the imported or Gossip generated private and public keys are disposable, because they work only for the time set when the delegation tag was generated. When that time expires the disposable keys also expire and it will be impossible to write any post. Then, if these disposable keys have been hacked, It will be possible to generate other disposable keys and a new delegation tag and start again anew, but with the same identity

This is what I understood. But many thanks again for your help!
Best

**Comment by optout21** [comment]
The events are posted technically under the identity (keypair) of Gossip, this is the 'disposable' delegatee identity.  The private key still needs to be unlocked to be able to post, but this is not the 'master' private key, not the delegator identity.

**Comment by mikedilger** [comment]
Just be aware that some clients won't recognize the delegation, and will see these new keys as an unknown person not tied to your offline identity. There is a bit of a tug-of-war between nostr devs as to whether this kind of delegation is a good idea or not. I'm agnostic.
