### ISSUE TITLE
Sqlite is too slow

### ISSUE THREAD

**Issue by WhiteCat6142** [mikedilger/gossip#422]
My laptop only has HDD.
So sqlite journaling makes a lot of lag.
After I move database to tmpfs, it gets better.

**Comment by mikedilger** [comment]
There are multiple causes of significant slowdown. Your slowdown might not be due to sqlite.

On startup, if you are using the run.sh command, cargo will do a lot of things especially if has been a day since you ran it last. On my machine (HDDs under ZFS) sometimes it takes 30 seconds on startup before it starts displaying any events.  But if I run the binary, it only takes 3 seconds or so to start up.  Subsequent runs start up fast.

If you moved to tmpfs and it got fast, it might be just because cargo has already done is slow daily thing.

If OTOH you are running a binary, then what you say is correct, sqlite is causing a performance issue for you. It would be a large project to move away from sqlite and I can't commit to doing it at this time.

**Comment by WhiteCat6142** [comment]
I just bind mount ~/.local/share/gossip .
Gossip binary is already complied and located on HDD.

**Comment by WhiteCat6142** [comment]
What I mention is that performance tuning is needed.
For example,
https://stackoverflow.com/questions/1711631/improve-insert-per-second-performance-of-sqlite

**Comment by WhiteCat6142** [comment]
Note to self:
it seems gossip use mutex for transactions.
https://github.com/mikedilger/gossip/blob/master/src/db/event.rs#L72
https://github.com/mikedilger/gossip/blob/master/src/globals.rs#L150

rusqlite has unlock_notify feature.
However, it may require too mush code changes.

**Comment by WhiteCat6142** [comment]
After following query, it becomes much better.
I don't know how to execute this with rusqlite.
Is there anyone can do this?

```sqlite3
pragma journal_mode = WAL;
pragma synchronous = normal;
pragma temp_store = memory;
PRAGMA mmap_size=268435456;
```

**Comment by mikedilger** [comment]
Thanks for looking into that @WhiteCat6142.  This can be run with rusqlite with the `db.pragma_update()` function.

If `temp_store` = memory, indexes would have to be recreated on startup, is that right? Is that fast?

**Comment by mikedilger** [comment]
Ok I've looked into it and the indices that would be in memory aren't the ones we create with SQL, but only temporary ones.  So I've put all of these pragmas into the code on the unstable branch.
