### ISSUE TITLE
Unable to deactivate a (specific) relay

### ISSUE THREAD

**Issue by dtonon** [mikedilger/gossip#433]
I'm unable to "deactivate" a specific relay: 
wss://filter.nostr.wine/npub10000003zmk89narqpczy4ff6rnuht2wu05na7kpnh3mak7z2tqzsv8vwqk?broadcast=true
unflagging the read/write/etc checkboxes. They come back. Same problem with the trash icon.

The log is spammed every sec with:

> websocket close error: WebSocket protocol error: Sending after closing is not allowed
Done picking relays: Unable to make further progress.
Minion wss://filter.nostr.wine/npub10000003z...  will restart in 0 seconds to continue persistent jobs

---

Branch: Unstable [3cf8d9cc]

**Comment by dtonon** [comment]
(Temporarily fixed by manually removing the relay from the db)

**Comment by mikedilger** [comment]
I was able to reproduce.

By throwing the error instead of swallowing it, I got it to stop connecting every 0 seconds (now it's every 120 seconds) and as a consequence somehow, you have time to uncheck the relay read/write boxes.  Not sure if it will tick them again after 120 seconds, I'll go try to find where that was happening.

**Comment by mikedilger** [comment]
I am going to presume the move to LMDB solved this, but reopen if it didn't.

**Comment by dtonon** [comment]
@mikedilger seems to work well for me.
