### ISSUE TITLE
Issue on searching: overload keeps on downloading notes and images

### ISSUE THREAD

**Issue by nbenaglia** [mikedilger/gossip#481]
In search menu, when I find a person and I want to view his posts, the overload process starts collecting all posts and images and it continues even if I exit the search menu and I go to "main feed" or "my notes".
I see the cache folder growing and growing.

In my opinion the expected behavior should be the overload process stops working when I exit the search menu.

**Comment by mikedilger** [comment]
I understand what you want and why you want it. But this is not easy to do.  It is not an overlord thread doing this that can be cancelled.  Rather, it is the fetcher queue.

If you switch to a separate page, the subscriptions to the relays do get cancelled.  But there is only one queue for data needing to be downloaded. There is no way to cancel some jobs from it. There isn't any record of why the job is in there.

I'm not against creating a way to cancel jobs and a record of why a job is there.  However, after thinking about it, I'm not sure what that record should say. Downloaded data isn't tightly associated with any given page, so it is not clear what should be cancelled as you switch pages. Some people want the client to keep downloading data so that they can switch back and the feed is all ready for them.  Other pages (not search) download their own stuff, often for the exact same reasons.  Gossip is not a  browser where pages are isolated processes. UI pages are not at all independent. It seems wildly complicated to try to make them behave that way, or to try to figure out what downloads ought to be cancelled in what circumstances.

So I'm not going to do this. But you are welcome to fork gossip and try yourself.
