### ISSUE TITLE
Doesn't work on OS X - M1 (arm64)

### ISSUE THREAD

**Issue by freQniK** [mikedilger/gossip#568]
Says the file is damaged:

<img width="268" alt="Screen Shot 2023-11-04 at 9 15 03 PM" src="https://github.com/mikedilger/gossip/assets/93114223/7f1741ee-0981-48f4-be4b-c4e4dd5996f2">

Downloaded the Darwin arm64 release.

**Comment by mikedilger** [comment]
dup of https://github.com/mikedilger/gossip/issues/398

It is not signed by an apple developer because I refuse to sign the contract with them which has egregious terms in it.

So you have to do some magic thing in order for it to allow you to run it. I can't remember that magic thing.

Or you can compile from source, which yields something you can trust even more so.

**Comment by tyiu** [comment]
The magic thing is running `sudo xattr -rd com.apple.quarantine /Applications/Gossip.app`

**Comment by cbeams** [comment]
I suggest the magic invocation be added to the release notes and readme. I knew about this problem and its solution from prior experience, but still had to go hunting `xattr` in the issues list here to find the exact args.

**Comment by mikedilger** [comment]
It is there already:

https://github.com/mikedilger/gossip/blob/master/packaging/macos/README.macos.txt

**Comment by cbeams** [comment]
So it is, thanks. I guess the point, though, is that I didn't see it there, despite explicitly looking for this information. I looked at the release notes (https://github.com/mikedilger/gossip/releases/tag/v0.10.1) and looked at the main readme and came up empty, so began searching through the issues here and found this one. Just FYI, cheers.
