### ISSUE TITLE
AUTH - user confirmation

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#572]
We need a setting wherein when a relay requests AUTH, the user is prompted to either AUTH or not.

Currently identity data leaks to relays, and sometimes users may not wish to expose their identity.

**Comment by mikedilger** [comment]
Branch for this work is 'auth'.  Here is the work that is finished, and the work that is still needed:

- [x] Augment Relay record to remember if a relay is approved or denied for both connection and authentication b193445cf6915eb3e7288385ff6f47ceef8bc3d6
- [x] Migrate to that new record b193445cf6915eb3e7288385ff6f47ceef8bc3d6
- [x] When AUTH request comes in, honor the relay setting.  If the relay setting is still `None`, store data in GLOBALS to signal the UI that the User needs to be asked, and provide ToOverlord message handlers to handle the user action by both storing the answer and signalling the relay to either AUTH or not. a0ef26df01cc8ec15deebdc3348d39e9050a6804
- [x] When a connection to a new relay happens, honor the connection setting.  If the connection setting is still `None`, store data in GLOBALS to signal the UI that the user needs to be asked, and provide ToOverlord message handlers to handle the user action by storing the answer and either starting the minion or not f0aad074d310cc5768733ecd09af75c010b00be0
- [x] Settings for both connection and auth, off by default, turning them on engages the new logic and requires per-relay approvals
- [ ] Relay pages in UI to offer switches for these two new settings
- [ ] UI to interact with the user to handle pending approvals - there may be many at once.

**Comment by mikedilger** [comment]
This issue is ready for UI work now.

**Comment by dtonon** [comment]
Final design after discussions on TM:

<img width="954" alt="Screenshot 2024-03-12 alle 22 58 11" src="https://github.com/mikedilger/gossip/assets/89577423/7306e7c8-228e-4513-b528-1c3f463d2f61">

**Comment by dtonon** [comment]
Notes about different and less intrusive approaches that can be evaluated for the future:

* We can move the modal content to a standard view and show a new menu item, that display an alert dot when there are new elements to review;

* We can show the permission request at the thread level (e.g., with an icon) so that the user knows that in order to view all the notes, he has to approve other relays;

**Comment by bu5hm4nn** [comment]
@dtonon Mike has merged the branch into unstable. Can you review and see if what we have is good for a 0.10 release?

**Comment by dtonon** [comment]
@bu5hm4nn it works well!
Some details:

![image](https://github.com/mikedilger/gossip/assets/89577423/0b274bac-7f65-44e7-b731-1c0ab84d19fc)

- [ ] A - In dark mode the _Decline_ button should also have the _Primary_ style (white)
- [ ] B - Would be nice if the scrolling was "external" to the modal padding, so on the extreme right
- [ ] C - The buttons on the backuground are still active to hover/press, even if the action is not triggered
- [ ] D - If possibile would be nice to lengthen the line going down a little bit
- [x] E - The light box background should be darker, both on dark and light theme - _Already fixed and pushed_
- [ ] F - Keep the alignment
- [ ] G - Trim the final slash

I would also remove the "wss://" to improve readability, but I suppose protocol is an important element in the approval evaluation, right @mikedilger?
Since encrypted protocol should be the standard, maybe in the future we can globally introduce a new way to visualize the protocol, adding a warning icon near the relays that are ws://. I will open an issue to track this idea.

**Comment by bu5hm4nn** [comment]
All are fixed on unstable, except for 'C'. That one is an egui bug I cannot easily fix. However once we use our own widgets, we can avoid doing the click ui action when disabled.

**Comment by mikedilger** [comment]
Since 99% of this is done, let's close this and I'll open an issue for 'C' separately.
