### ISSUE TITLE
gossip does not have an exit button (linux)

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#614]
In linux, gossip does not have a close window button or exit button.  So I have to kill the process.  I've noticed in recent versions, that even a regular kill signal does not cause it to exit and I have to kill -9.  Strange, and I'm wondering, would it be too much to add some type of graceful exit option to gossip?  I wonder why it's ignoring SIGTERM too...

**Comment by mikedilger** [comment]
Window managers generally have a way to close a window. Do you not have an 'x' in the upper right to close it? I didn't bother adding a quit because I didn't run into a case where the window manager didn't already present a way to quit. We just wait on eframe::run_native() to exit.

We don't capture any signals, we have no special signal handling. That's actually odd among programs that I write: usually a program this big has some kind of special signal handling.  So I do not know why SIGTERM fails. It is probably something that egui/eframe/winit does when we give it control over the main thread.

**Comment by jeremyd** [comment]
I run a tiling WM (sway).  It does not present a close button and is borderless other than what the app presents.  I'll do some more digging on this in the code, perhaps there is an egui flag I can set..  I have not run gnome in a long time but I am curious if the exit button on the window allows for close or not given the SIGTERM behavior I'm experiencing.  I also used to be able to CTRL-C in the terminal where gossip was launched to kill it, but that also no longer works.  Thanks for the response, this issue is mostly a bookmark to remind me to look into this.

**Comment by jeremyd** [comment]
On further investigation, I am able to close gossip with the keyboard shortcut for closing windows in sway.  Closing this issue.
