### ISSUE TITLE
I can't tag Alex Gleason

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#693]
Try it.

@bu5hm4nn

**Comment by mikedilger** [comment]
Also when I tag somebody, the preview of who will be tagged below the note does not include it.  It is as if the raw draft content doesn't actually contain the nostr:npub... string.  This breaks code post.rs from line 641-663

**Comment by bu5hm4nn** [comment]
I'll look into the lines you mentioned.

But you're right, the draft content does not contain the string until you hit send or "Raw preview" because it would break the textedit cursor handling. Eventually we will have to write our own richtext editor. Here's me tagging Alex:

https://github.com/mikedilger/gossip/assets/3328670/4402e909-4f74-4a55-a2cd-6d238e808150

**Comment by bu5hm4nn** [comment]
Ok, now I see which lines you mean. That basically got replaced by the blue text and hover popups for the new tagging interface. But it was intended to still show in raw preview. The bug is that it just references the wrong string. If you change line 644 from `NostrBech32::find_all_in_string(&app.draft_data.draft)` to `NostrBech32::find_all_in_string(&app.draft_data.raw)` then it will work in raw-preview.

<img width="620" alt="Screenshot 2024-03-25 at 22 48 55" src="https://github.com/mikedilger/gossip/assets/3328670/2b8c2e32-500a-4fab-a0e1-7c7958838c7d">

**Comment by mikedilger** [comment]
Ok try to tag him by typing "Alex Gleason".

**Comment by bu5hm4nn** [comment]
https://github.com/mikedilger/gossip/assets/3328670/be5671ce-a2fd-4594-a4a9-ec41260fc6ea

1) we stop the tagging search when you hit space, this means you can't specify which alex
2) his nip5 doesn't start with `alexgleason`, it's `alex_at_gleasonator` so typing `alexgl` won't bring him up
3) I don't follow him, otherwise he would have floated to the top of the list

I see 2 things we can improve:
1) remove spaces in the name when searching, that would bring him up when typing `alexgl`
2) also float people up that are on lists other than following

**Comment by mikedilger** [comment]
I think your work yesterday pretty much solves my issue, so closing.
